version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: db_journey
    restart: always
    env_file:
      - .env.dev
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:


